apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'boldbi-cloud-prod'
spec:
  project: default
  source:
    repoURL: 'https://github.com/RahulSubash/boldbi-cloud-test.git'
    path: production
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: boldbi-cloud-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true